//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
pub struct SetBuffer {
      
              
          pub buffer: solana_program::pubkey::Pubkey,
          
              
          pub idl: solana_program::pubkey::Pubkey,
          
              
          pub authority: solana_program::pubkey::Pubkey,
          
              
          pub program_id: solana_program::pubkey::Pubkey,
      }

impl SetBuffer {
  pub fn instruction(&self, args: SetBufferInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: SetBufferInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.buffer,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.idl,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.program_id,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = SetBufferInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::UPLOAD_IDL_ANCHOR_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshDeserialize, BorshSerialize)]
pub struct SetBufferInstructionData {
            discriminator: [u8; 8],
            }

impl SetBufferInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [13, 212, 241, 0, 78, 93, 17, 51],
                                }
  }
}

impl Default for SetBufferInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetBufferInstructionArgs {
                  pub seed: String,
      }


/// Instruction builder for `SetBuffer`.
///
/// ### Accounts:
///
                ///   0. `[writable]` buffer
                ///   1. `[writable]` idl
                ///   2. `[signer]` authority
          ///   3. `[]` program_id
#[derive(Clone, Debug, Default)]
pub struct SetBufferBuilder {
            buffer: Option<solana_program::pubkey::Pubkey>,
                idl: Option<solana_program::pubkey::Pubkey>,
                authority: Option<solana_program::pubkey::Pubkey>,
                program_id: Option<solana_program::pubkey::Pubkey>,
                        seed: Option<String>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl SetBufferBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn buffer(&mut self, buffer: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.buffer = Some(buffer);
                    self
    }
            #[inline(always)]
    pub fn idl(&mut self, idl: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.idl = Some(idl);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn program_id(&mut self, program_id: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.program_id = Some(program_id);
                    self
    }
                    #[inline(always)]
      pub fn seed(&mut self, seed: String) -> &mut Self {
        self.seed = Some(seed);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = SetBuffer {
                              buffer: self.buffer.expect("buffer is not set"),
                                        idl: self.idl.expect("idl is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        program_id: self.program_id.expect("program_id is not set"),
                      };
          let args = SetBufferInstructionArgs {
                                                              seed: self.seed.clone().expect("seed is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `set_buffer` CPI accounts.
  pub struct SetBufferCpiAccounts<'a, 'b> {
          
                    
              pub buffer: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub idl: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub program_id: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `set_buffer` CPI instruction.
pub struct SetBufferCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub buffer: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub idl: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub program_id: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: SetBufferInstructionArgs,
  }

impl<'a, 'b> SetBufferCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: SetBufferCpiAccounts<'a, 'b>,
              args: SetBufferInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              buffer: accounts.buffer,
              idl: accounts.idl,
              authority: accounts.authority,
              program_id: accounts.program_id,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(4+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.buffer.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.idl.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.program_id.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = SetBufferInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::UPLOAD_IDL_ANCHOR_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.buffer.clone());
                        account_infos.push(self.idl.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.program_id.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `SetBuffer` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` buffer
                ///   1. `[writable]` idl
                ///   2. `[signer]` authority
          ///   3. `[]` program_id
#[derive(Clone, Debug)]
pub struct SetBufferCpiBuilder<'a, 'b> {
  instruction: Box<SetBufferCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SetBufferCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(SetBufferCpiBuilderInstruction {
      __program: program,
              buffer: None,
              idl: None,
              authority: None,
              program_id: None,
                                            seed: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn buffer(&mut self, buffer: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.buffer = Some(buffer);
                    self
    }
      #[inline(always)]
    pub fn idl(&mut self, idl: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.idl = Some(idl);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn program_id(&mut self, program_id: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.program_id = Some(program_id);
                    self
    }
                    #[inline(always)]
      pub fn seed(&mut self, seed: String) -> &mut Self {
        self.instruction.seed = Some(seed);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = SetBufferInstructionArgs {
                                                              seed: self.instruction.seed.clone().expect("seed is not set"),
                                    };
        let instruction = SetBufferCpi {
        __program: self.instruction.__program,
                  
          buffer: self.instruction.buffer.expect("buffer is not set"),
                  
          idl: self.instruction.idl.expect("idl is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          program_id: self.instruction.program_id.expect("program_id is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct SetBufferCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            buffer: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                idl: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                program_id: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        seed: Option<String>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

