//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum MetadataProgramError {
    /// 6000 - Only the program upgrade authority can initialize the IDL account
    #[error("Only the program upgrade authority can initialize the IDL account")]
    WrongAuthority = 0x1770,
    /// 6001 - The program account is not executable
    #[error("The program account is not executable")]
    NotExecutable = 0x1771,
    /// 6002 - The program account is not a program. Not owned by the BPF loader
    #[error("The program account is not a program. Not owned by the BPF loader")]
    NotAProgram = 0x1772,
    /// 6003 - The program account should not be a program data account
    #[error("The program account should not be a program data account")]
    ShouldBeProgramAccount = 0x1773,
}

impl solana_program::program_error::PrintProgramError for MetadataProgramError {
    fn print<E>(&self) {
        solana_program::msg!(&self.to_string());
    }
}

