//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub(crate) mod upload_idl_anchor;
  
      pub use self::upload_idl_anchor::UploadIdlAnchorError;
  
