//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};


  /// `upload_idl_anchor` program ID.
  pub const UPLOAD_IDL_ANCHOR_ID: Pubkey = pubkey!("idLB41CuMPpWZmQGGxpsxbyGDWWzono4JnFLJxQakrE");

