//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};


  /// `metadata_program` program ID.
  pub const METADATA_PROGRAM_ID: Pubkey = pubkey!("pmetaypqG6SiB47xMigYVMAkuHDWeSDXcv3zzDrJJvA");

